### PR TITLE
Fix several minor typos in some notebooks and an example file

### PR DESCRIPTION
**Pull request by jamestiotio**
# Description

This PR fixes several minor typos in some notebooks and an example file.

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @jamestiotio Thank you very much for your pull request!

**Comment by jamestiotio** [comment]
Hmm, I am not sure why one of the tests failed and why the test coverage decreased significantly since my changes are simply lexical in nature and they should not have any functional changes. 🤔

**Review by beat-buesser — APPROVED** [review]
@jamestiotio Thank you very much! It looks good to me.

**Comment by jamestiotio** [comment]
Oh seems like it passes all the tests on the latest re-run. Thanks, @beat-buesser!

**Pull request merged**
