### PR TITLE
Add an option to SklearnClassifier to use logits

### LINKED ISSUE #826: SklearnClassifier produces probabilities instead of logits for DeepFool
**Describe the bug**
Running `DeepFool` on a `SklearnClassifier` results in probabilities instead of logits being provided to `DeepFool`.

**To Reproduce**
Pseudocode only
```python
X, y = ...
classifier = SklearnClassifier(model=SVC(kernel='linear', probability=True))
classifier.fit(X, y)
attack = DeepFool(classifier=classifier)

adversarial_examples = attack.generate(X)
```

Results in the warning:

> It seems that the attacked model is predicting probabilities. DeepFool expects logits as model output to achieve its full attack strength.

**Expected behavior**
The `SklearnClassifier` should use `predict_log_proba` instead of `predict_proba` when providing probability estimates to the deepfool attack.

**System information:**
 - Windows 10 ver 2004 build 19041.685
 - Python version: 3.8.5
 - ART version: 1.5.0
 - TensorFlow / Keras / PyTorch / MXNet version: N/A

### PR DESCRIPTION
**Pull request by zacps**
# Description

The `DeepFool` attack expected logits instead of probabilities. Currently there is no way to provide logits from an `SklearnClassifier`. This PR adds the ability to change `.predict()` to provide logits.

Fixes #826 

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing

Tests show little difference with and without logits on one dataset.

**Test Configuration**:
- OS: Windows 10
- Python version: 3.8.5

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @zacps Thank you for opening the pull request! I have change the target from `main` to `dev_1.6.0` for the next release of ART.

**Comment by zacps** [comment]
My preliminary tests don't show much of a difference, but it doesn't seem to have broken anything.

**Comment by beat-buesser** [comment]
Hi @zacps Thank you very much! Sorry, I didn't notice you push immediately. I restarted the tests because of the spurious test fail.

**Comment by zacps** [comment]
```
======================================================================
FAIL: test_emp_robustness_mnist (tests.metrics.test_metrics.TestMetrics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/adversarial-robustness-toolbox/adversarial-robustness-toolbox/tests/metrics/test_metrics.py", line 63, in test_emp_robustness_mnist
    self.assertAlmostEqual(emp_robust, 1.000369094488189, 4)
AssertionError: 1.000316770748484 != 1.000369094488189 within 4 places (5.232373970498472e-05 difference)
```

The same failure IIRC, probably need to make the check less sensitive.

**Review by beat-buesser — APPROVED** [review]
Hi @zacps Thank you very much for your pull request!

**Pull request merged**
