### PR TITLE
Updates for DPatch

### PR DESCRIPTION
**Pull request by beat-buesser**
Signed-off-by: Beat Buesser <beat.buesser@ie.ibm.com>

# Description

This pull request provides minor updates to `DPatch` to improve initialisation of the patch, the iteration over batches, and handling of estimators without `clip_values`.

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mathsinn — CHANGES_REQUESTED** [review]
Hi @beat-buesser those changes look all good to me. Just one additional observation in this context: I think the computation of predictions in the untargeted case (l.152)
```
predictions = self.estimator.predict(x=patched_images)
```
should occur outside the optimization loop starting in l.126. Otherwise, effectively, the objective of the optimization changes in each iteration. 

What do you think?

**Comment by beat-buesser** [comment]
@mathsinn I think that makes sense to already include it here. I was initially planning to separate minor and major updates.

**Comment by beat-buesser** [comment]
@mathsinn I have moved the entire definition of `patch_target` outside of the iteration loop.

**Review by mathsinn — APPROVED** [review]
Thanks @beat-buesser - looks good to me!

**Pull request merged**
