### PR TITLE
Addition of SmoothAdversarial and MACER Training in the Randomized Smoothing Module

### PR DESCRIPTION
**Pull request by archit-g**
# Description

- Addition of SmoothAdversarial and MACER Training in the Randomized Smoothing Module
- Support for SmoothAdversarial implementation in PyTorch and Tensorflow
- Support for MACER implementation in PyTorch
- Example notebooks for the new modules added
- Unit tests for the new modules added

Links to Paper and Authors' code repository:
- SmoothAdversarial: https://arxiv.org/abs/1906.04584 (https://github.com/Hadisalman/smoothing-adversarial/)
- MACER: https://openreview.net/pdf?id=rJx1Na4Fwr (https://github.com/RuntianZ/macer)

Fixes # (issue)

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Adding @keykholt for updates.

**Comment by tirthmehta05** [comment]
Hi @beat-buesser can you please trigger style checks on the new commit

**Comment by archit-g** [comment]
Adding @rahmati and @pratik18v for updates.

**Comment by archit-g** [comment]
Hi @beat-buesser, sorry for being away from this PR for a while. We were hoping to resolve the pending failures and new recent conflicts by picking up this PR again. But the last logs seemed to be expired, can you please kindly trigger the build on this again? Sorry for the inconvenience. Thanks!

**Comment by beat-buesser** [comment]
Hi @archit-g That's great! Sorry for my late response. There seem to be some merge conflicts with the target branch which might hinder the tests to run. Can you rebase your commits onto branch `dev_1.12.0` and update the target branch of the PR to `dev_1.12.0`?

**Comment by tirthmehta05** [comment]
Hi @beat-buesser , thanks for your suggestion and we have rebased our commits onto branch dev_1.12.0 and updated the target branch of the PR to dev_1.12.0.
Can you please approve the workflows?

**Pull request closed without merging**
