### PR TITLE
Zoo documentation

### PR DESCRIPTION
**Pull request by LucaSchinnerl**
# Description

Added additional documentation and cleaned up the compare function in the ZOO-attack for better understanding

Fixes # (issue)

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @LucaSchinnerl Thank you very much for your pull request. We'll take a closer look soon.

**Review by beat-buesser — CHANGES_REQUESTED** [review]
Hi @LucaSchinnerl The improvements look good to me!

Should we add typing to the new method `_compare`, e.g. `_compare(self, object1: Any, object2: Any) -> bool`?

The style check has found a few minor items, could you please take a look? You can fix most of them by running Black formatter version 21.12b0 with `black --line-length 120 art/`.

**Comment by LucaSchinnerl** [comment]
Hi @beat-buesser, 

thank you very much for your suggestions. I think typing is a good idea.

I will fix the formatting later today/tomorrow.

**Review by beat-buesser — APPROVED** [review]
Hi @LucaSchinnerl Thank you very much for your contribution to ART! The changes look good to me.

Btw, please let me know if you would be interested to work on future projects for ART!

**Pull request merged**
