### PR TITLE
Fixes torchaudio.functional.magphase use for Deep Speech 2 version 3

### LINKED ISSUE #1549: Deep Speech 2 Version 3.0 fails on PyTorch 1.10 / TorchAudio 0.10
**Describe the bug**
Deep Speech 2 model fails when using V3.0, at least for torch 1.10 / torchaudio 1.11.

It fails at this line:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/speech_recognition/pytorch_deep_speech.py#L791
```
spectrogram, _ = torchaudio.functional.magphase(transformed_input)
```

I get the following stack trace on both GPU and CPU:
```
  File "/workspace/armory/scenarios/scenario.py", line 267, in run_benign                                                                                                            
    y_pred = self.model.predict(x, **self.predict_kwargs)                                                                                                                            
  File "/workspace/art/estimators/speech_recognition/pytorch_deep_speech.py", line 364, in predict                                                                                   
    inputs, _, input_rates, _, batch_idx = self._transform_model_input(x=x_preprocessed)                                                                                             
  File "/workspace/art/estimators/speech_recognition/pytorch_deep_speech.py", line 795, in _transform_model_input                                                                    
    spectrogram, _ = torchaudio.functional.magphase(transformed_input)                                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py", line 58, in wrapped                                                                            
    return func(*args, **kwargs)                                                                                                                                                     
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/functional/functional.py", line 795, in magphase                                                                           
    phase = angle(complex_tensor)                                                                                                                                                    
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py", line 58, in wrapped                                                                            
    return func(*args, **kwargs)                                                                                                                                                     
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/functional/functional.py", line 771, in angle                                                                              
    return torch.atan2(complex_tensor[..., 1], complex_tensor[..., 0])                                                                                                               
RuntimeError: "atan2_cuda" not implemented for 'ComplexFloat'  
```
as well as the warning before that of the deprecation of `torchaudio.functional.magphase`:
```
/workspace/art/estimators/speech_recognition/pytorch_deep_speech.py:795: UserWarning: torchaudio.functional.functional.magphase has been deprecated and will be removed from 0.11 rel
ease. Please convert the input Tensor to complex type with `torch.view_as_complex` then use `torch.abs` and `torch.angle`. Please refer to https://github.com/pytorch/audio/issues/13
37 for more details about torchaudio's plan to migrate to native complex type.                                                                                                       
  spectrogram, _ = torchaudio.functional.magphase(transformed_input)
```

**To Reproduce**
```
# First, install github.com/SeanNaren/deepspeech.pytorch@V3.0
from art.estimators.speech_recognition import PyTorchDeepSpeech
import numpy as np
model = PyTorchDeepSpeech(pretrained_model="librispeech")
assert model._version == 3
x = np.random.random((1, 238400)).astype(np.float32)
model.predict(x)
```

**Expected behavior**
Should just generate the magnitude representation of the complex input.

**System information (please complete the following information):**
 - OS - Ubuntu 20.04
 - Python version - 3.8.10
 - ART version or commit number - 1.9.1
 - TensorFlow / Keras / PyTorch / MXNet version - torch is 1.10.2, torchaudio is 1.10.2

### PR DESCRIPTION
**Pull request by davidslater**
# Description

Added conditional logic for version 3 to use updated torch.abs instead of torchaudio.functional.magphase.

Fixes #1549

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by davidslater** [comment]
@beat-buesser not sure which branch you want this PR pointed at.

**Comment by davidslater** [comment]
The style check failure
```
Run mypy art
art/estimators/speech_recognition/pytorch_deep_speech.py:26: error: Module 'pkg_resources' has no attribute 'packaging'
Found 1 error in 1 file (checked 261 source files)
Error: Process completed with exit code 1.
```
may be due to the way in which pkg_resources handles external imports:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import packaging
>>> packaging
<module 'pkg_resources.extern.packaging' (<pkg_resources.extern.VendorImporter object at 0x7ffeb84bd450>)>
```
Doing this will fail, for instance:
```
>>> from pkg_resources.packaging import version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pkg_resources.packaging'
```
An alternative could be to the following: 
```
>>> from pkg_resources.extern import packaging
```
or
```
from pkg_resources.extern.packaging import version
```
However, I have no idea of the stability of `pkg_resources` structure.

**Comment by beat-buesser** [comment]
@davidslater I have checked a few other libraries and it looks like we have to add for now an ignore exception with `from pkg_resources import packaging  # type: ignore[attr-defined]`

**Review by beat-buesser — APPROVED** [review]
Hi @davidslater Thank you very much! It looks good to me.

**Pull request merged**
