### PR TITLE
Feat: Add three new Membership Inference attacks

### PR DESCRIPTION
**Pull request by iamsh4shank**
# Description

Added three new types of membership inference attacks, these are as follows - 
* SIF Attack
* Blind Membership inference Attack
* White Box based Membership Inference Attacks

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] I ran test files to test the changes

**Test Configuration**:
- Ubuntu 20
- 3.9
- 1.15
- TensorFlow / Keras / PyTorch / MXNet version - all in the newest version

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @iamsh4shank Thank you very much for your interest in ART and working on contributing new inference attacks! We will review this PR as soon as possible.

**Comment by iamsh4shank** [comment]
> Hi @iamsh4shank It looks like something failed in the new unit tests like unexpected arguments, etc. Could you please take a look?

Yep sure will check and update the pull request soon

**Comment by iamsh4shank** [comment]
@beat-buesser could you please once run the CI/CD?

**Comment by iamsh4shank** [comment]
@beat-buesser I modified the commit, now it should fix almost all of the checks. I have a question here in this https://github.com/Trusted-AI/adversarial-robustness-toolbox/actions/runs/6130115176/job/16713558817?pr=2271, as here there is no installation for the cv2 that causes a few failures. So should I add cv2 in these files?

**Comment by iamsh4shank** [comment]
Hi is there any update on this?

**Comment by beat-buesser** [comment]
Hi @iamsh4shank Sorry for the delay. We think the attacks are a great addition to ART's current inference attacks. We'll add a more detailed technical review soon. A few items I have noticed from a high-level review: could you please start adding unit tests for each attack and function in `tests/` following the pytest pattern, update/add all docstrings following ART's format and add typing to all functions and methods?

**Comment by iamsh4shank** [comment]
> Hi @iamsh4shank Sorry for the delay. We think the attacks are a great addition to ART's current inference attacks. We'll add a more detailed technical review soon. A few items I have noticed from a high-level review: could you please start adding unit tests for each attack and function in `tests/` following the pytest pattern, update/add all docstrings following ART's format and add typing to all functions and methods?

Yep sure, I will start working on the tests

**Pull request closed without merging**
