### PR TITLE
Create backdoor-clean-label

### PR DESCRIPTION
**Pull request by OrsonTyphanel93**
# Description

This code transforms the audios dirty label backdoor attack into a truly robust clean label attack!, 

Please include a summary of the change, motivation and which issue is fixed. Any dependencies changes should also be included.

Fixes # (issue)

## Type of change

This class implements a clean label attack, in particular for poisoning attacks with clean labels. The main contributions of this are as follows:

Robust clean label backdoor attack !

Please check all relevant options.

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ]  This code defines a class " PoisoningAttackCleanLabelBackdoor"  that performs a true clean label backdoor robust attack. 

- [ ]  When the poison method is called, it applies the trigger function to the input data and returns the poisoned data with the same clean labels as the original data and applies an alpha factor to make the attack very imperceptible even if the audio trigger has a high volume!

### CODE REVIEW

**Comment by OrsonTyphanel93** [comment]
Hi team i just created the entire notebook, which alludes to this change , 

https://github.com/OrsonTyphanel93/adversarial-robustness-toolbox/blob/main/create_backdoor_attacks_clean_label_%28_Audio%29.ipynb

**Comment by OrsonTyphanel93** [comment]
`python
import logging
from typing import Callable, Optional, Tuple, Union


import numpy as np


from art.attacks.attack import PoisoningAttackBlackBox


logger = logging.getLogger(__name__)


class PoisoningAttackCleanLabelBackdoor(PoisoningAttackBlackBox):
   """
   A clean-label backdoor attack that injects a trigger into clean data samples without changing their labels.


   This attack is useful for poisoning machine learning models with a backdoor trigger while maintaining the original labels.


   :param trigger_func: A callable function that applies the backdoor trigger to input data samples.
   """


   attack_params = PoisoningAttackBlackBox.attack_params + ["trigger_func"]
   _estimator_requirements = ()


   def __init__(self, trigger_func: Callable) -> None:
       """
       Initialize a PoisoningAttackCleanLabelBackdoor instance.


       :param trigger_func: A callable function that applies the backdoor trigger to input data samples.
       """
       super().__init__()
       self.trigger_func = trigger_func
       self._check_params()


   def poison(
       self, x: np.ndarray, y: Optional[np.ndarray] = None, broadcast: bool = False, **kwargs
   ) -> Tuple[np.ndarray, np.ndarray]:
       """
       Inject a backdoor trigger into clean data samples.


       :param x: Clean data samples.
       :param y: Target labels for the clean data samples.
       :param broadcast: If True, broadcast target labels to match the number of samples in x.
       :param kwargs: Additional keyword arguments (not used).


       :return: Poisoned data samples with clean labels.
       """
       if y is None:
           raise ValueError("Target labels `y` need to be provided for a targeted attack.")


       if broadcast:
           y_attack = np.broadcast_to(y, (x.shape[0], y.shape[0]))
       else:
           y_attack = np.copy(y)


       num_poison = len(x)
       if num_poison == 0:
           raise ValueError("Must input at least one poison point.")
       poisoned = np.copy(x)


       if callable(self.trigger_func):
           # Apply the trigger function to the input data
           poisoned = self.trigger_func(poisoned)


       # Labels remain unchanged
       poisoned_labels = y_attack


       return poisoned, poisoned_labels


   def _check_params(self) -> None:
       if not callable(self.trigger_func):
           raise ValueError("Trigger function must be callable.")


   @staticmethod
   def is_broadcast(broadcast: bool) -> bool:
       """
       Check if the broadcast parameter is a boolean value.


       :param broadcast: The broadcast parameter to check.


       :return: True if broadcast is a boolean, False otherwise.
       """
       return isinstance(broadcast, bool)


   def _validate_inputs(self, x: np.ndarray, y: Optional[np.ndarray] = None, broadcast: bool = False) -> None:
       """
       Validate input parameters.


       :param x: Clean data samples.
       :param y: Target labels for the clean data samples.
       :param broadcast: If True, broadcast target labels to match the number of samples in x.


       :raises ValueError: If input parameters are invalid.
       """
       if y is None:
           raise ValueError("Target labels `y` need to be provided for a targeted attack.")


       if not self.is_broadcast(broadcast):
           raise ValueError("`broadcast` must be a boolean value.")

`

**Comment by OrsonTyphanel93** [comment]
I have "19 workflows awaiting approval" which I believe is due to the DCO.

**Comment by OrsonTyphanel93** [comment]
how to solve these DCO github problems to merge the class #backdoor clean-label  audios created? 

Thanks !

**Comment by beat-buesser** [comment]
Closing because of inactivity, please reopen if still current.

**Pull request closed without merging**
