### PR TITLE
fix: fixed np.sum in art/defences/postprocessor/gaussian_noise.py

### LINKED ISSUE #1675: Problem with predictions using Gaussian Noise defence
### Discussed in https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/1674

<div type='discussions-op-text'>

<sup>Originally posted by **GianlucaMega** May  9, 2022</sup>
Hello,
I'm trying to use Gaussian noise as postprocessing defence but I'm getting an error when calling the predict method of the classifier. I'm using the code from the keras example of this repo which I'm reporting here:

```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adam
import numpy as np
from art.attacks.evasion import FastGradientMethod
from art.estimators.classification import KerasClassifier
from art.utils import load_mnist, compute_accuracy
from art.defences.postprocessor import GaussianNoise

(x_train, y_train), (x_test, y_test), min_pixel_value, max_pixel_value = load_mnist()

model = Sequential()
model.add(Conv2D(filters=4, kernel_size=(5, 5), strides=1, activation="relu", input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(filters=10, kernel_size=(5, 5), strides=1, activation="relu", input_shape=(23, 23, 4)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(100, activation="relu"))
model.add(Dense(10, activation="softmax"))

model.compile(loss=categorical_crossentropy, optimizer=Adam(learning_rate=0.01), metrics=["accuracy"])

gauss = GaussianNoise()
classifier = KerasClassifier(model=model, clip_values=(min_pixel_value, max_pixel_value), use_logits=False, postprocessing_defences=gauss)

classifier.fit(x_train, y_train, batch_size=64, nb_epochs=3)
preds = classifier.predict(x_test)
acc = compute_accuracy(preds, y_test)
```

and this is the error that is prompted:
```
---------------------------------------------------------------------------
ValueError  Traceback (most recent call last) [<ipython-input-5-eec5e88d0d3f>](https://localhost:8080/#) in <module>()
     37 
     38 classifier.fit(x_train, y_train, batch_size=64, nb_epochs=3)
---> 39 preds = classifier.predict(x_test)
     40 acc = compute_accuracy(preds, y_test)

3 frames
[/usr/local/lib/python3.7/dist-packages/art/defences/postprocessor/gaussian_noise.py](https://localhost:8080/#) in __call__(self, preds)
     71                 post_preds[post_preds < 0.0] = 0.0
     72                 sums = np.sum(post_preds, axis=1)
---> 73                 post_preds /= sums
     74         else:
     75             post_preds[post_preds < 0.0] = 0.0

ValueError: operands could not be broadcast together with shapes (10000,10) (10000,) (10000,10)
```

Is this a bug or am I doing something wrong?

Thank you for the support</div>

### PR DESCRIPTION
**Pull request by GianlucaMega**
Signed-off-By: GianlucaMega <megagianluca.mg@gmail.com>

# Description

The GaussianNoise postprocessing defence could not handle mini-batches due to a problem with the `sums` variable, in particular with the np.sum. The original instruction has been changed into `np.sum(post_preds, axis=1, keepdims=True)`

Fixes #1675 

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] tests/defences/test_gaussian_noise.py

**Test Configuration**:
- OS Kali Linux 2022.1
- Python version 3.9.7
- ART version or commit number 1.10.2
- TensorFlow / Keras / PyTorch / MXNet version TF:2.8.0, Keras:2.8.0, PyTorch:1.11.0+cu102, mx:1.8.0

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @GianlucaMega Thank you very much for you pull request, that's amazing! May I ask you for one more step, could you please sign-off the commit to pass the DCO check? Follow these steps:

1. Go to your local copy of your branch `dev_1.10.2` where you created the commit
2. Run `git rebase HEAD~1 --signoff`
3. Force push your changes to overwrite your remote branch with `git push --force-with-lease origin dev_1.10.2`

**Comment by GianlucaMega** [comment]
Sorry for the inconvenience, I've fixed it!

**Review by beat-buesser — APPROVED** [review]
Hi @GianlucaMega Thank you very much for your help and congratulations to your first contribution to ART! Please let me know when you are interested in working on a new project for ART.

**Comment by GianlucaMega** [comment]
Thank you very much @beat-buesser for the support and guidance you gave me and congratulations for ART, amazing library!

**Pull request merged**
