### PR TITLE
Update get_started_tensorflow.py

### PR DESCRIPTION
**Pull request by bluemurder**
Preventing error `RuntimeError: tf.placeholder() is not compatible with eager execution.`

# Description

Please include a summary of the change, motivation and which issue is fixed. Any dependencies changes should also be included.

Fixes # (issue)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @bluemurder Thank you very much for using ART and for improving the TensorFlow example!

May I ask you to sign-off the commit to pass the DCO check?

**Comment by beat-buesser** [comment]
Hi @bluemurder Can you try:

1. In your local branch, run: `git rebase HEAD~3 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin patch-1`

**Comment by bluemurder** [comment]
mm not sure why git gives me errors when trying to overwrite the branch: `git push --force-with-lease origin patch-1`.
If needed I can close the pull request providing a new pull request with a single clean commit with correct signoff.

**Comment by beat-buesser** [comment]
Hi @bluemurder Ok, I agree closing and opening a new pull request might be easier.

**Pull request closed without merging**
