### PR TITLE
Update projected_gradient_descent_pytorch.py [Solve non-writable NumPy array and device mismatch issues]

### PR DESCRIPTION
**Pull request by salomonhotegni**
# Description

This pull request addresses two issues in the `ProjectedGradientDescent` attack of the Adversarial Robustness Toolbox (ART):

1. A UserWarning indicating that a given NumPy array is not writable, leading to potential undefined behavior when converting it to a PyTorch tensor.
2. A RuntimeError caused by tensors being on different devices (CPU and CUDA) during the `_projection` function.

The solution involves copying the non-writable NumPy array to ensure it is writable and modifying the tensor conversion in the `_projection` function to ensure all tensors are on the same device.

Fixes # (issue)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

I have performed the following tests to verify the changes:

- [x] Verified that the UserWarning about non-writable NumPy arrays no longer appears.
- [x] Confirmed that the RuntimeError related to device mismatch is resolved.

**Test Configuration**:
- OS: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- Python version: 3.9.7
- ART version: 1.18.0
- PyTorch version: 1.13.1+cu117

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My changes have been tested using both CPU and GPU devices

---

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @salomonhotegni Could you please fix the DCO check?

**Review by beat-buesser — CHANGES_REQUESTED** [review]
Hi @salomonhotegni Could you please also make the same change in line 500?

**Comment by beat-buesser** [comment]
Please run Python formatter `black` with version `black==21.12b0` using command `black --line-length 120 --check art/` to fix the failing style checks.

**Comment by salomonhotegni** [comment]
> Hi @salomonhotegni Could you please also make the same change in line 500?

Sure!

**Comment by beat-buesser** [comment]
Hi @salomonhotegni Thank you very much. To pass the DCO check, could you please add your signed-off-by line to every commit in this branch using the following commands:

- In your local branch, run: `git rebase HEAD~2 --signoff`
- Force push your changes to overwrite the branch: `git push --force-with-lease origin my-feature-branch`

**Comment by beat-buesser** [comment]
@salomonhotegni Could you pleas also take a look at updating the code to pass the style checks with the instructions above?

**Comment by beat-buesser** [comment]
Hi @salomonhotegni Could you please run command `black --line-length 120 --check art/` with version `black==21.12b0` to make the style check pass? Please let me know if you need help from me.

**Comment by beat-buesser** [comment]
Thank you for fixing DCO.

**Review by beat-buesser — APPROVED** [review]
Hi @salomonhotegni Thank you very much for your first contribution to ART!

**Pull request merged**
