### PR TITLE
Update scikit-learn requirement to >=0.22.2,<1.4.0

### LINKED ISSUE #1953: Update version of scikit-learn in setup.py and CI yml files
### Discussed in https://github.com/Trusted-AI/adversarial-robustness-toolbox/discussions/1950

<div type='discussions-op-text'>

<sup>Originally posted by **sr1998** December  3, 2022</sup>
Hi, is it possible for the library to support newer versions of scikit-learn? At the moment it supports scikit-learn<1.1.0,>=0.22.2  but I also tested part of ART with scikit-learn 1.1.2 and it works like a charm. The question is of course whether everything will keep working which you know better of course. 

I hope support for newer versions of scikit-learn, at least 1.1.2 for me, is possible in the near future. I look forward to any reply.</div>

### PR DESCRIPTION
**Pull request by jamesmyatt**
# Description

Scikit-learn 1.1.x is over 1 year old. Also Python 3.10 is over 2 years old.

Fixes #1953, 
Replaces #1964

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

* CI

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] My changes have been tested using both CPU and GPU devices

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @jamesmyatt Thank you very much! I have started the unit-test workflows for this PR.

**Comment by jamesmyatt** [comment]
@beat-buesser There seems to be a problem with Codecov:

    [2023-12-13T14:18:25.530Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

**Comment by beat-buesser** [comment]
Hi @jamesmyatt Could you please take a look at one of the new runs? It seems that Python 3.11 is not yet available. I suggest we remove the second new run for Python 3.11 and also remove the oldest run for 0.24.2.

**Comment by jamesmyatt** [comment]
Removing 0.24.2 makes sense.

Looks like the issue for python 3.11 is the version of numba that's pinned.

**Comment by beat-buesser** [comment]
You're right. Can you try if it is possible to upgrade `numba` too? If I remember correctly it depends on the `numpy` version.

**Comment by jamesmyatt** [comment]
@beat-buesser Can you approve the workflows, please?

**Comment by beat-buesser** [comment]
Fixed by #2372

**Pull request closed without merging**
