### PR TITLE
Add drop_last option to method fit of PyTorchClassifier 

### LINKED ISSUE #1723: batch_norm error in fit() at end of training epoch
**Describe the bug**
At the end of [this](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.10.2/art/estimators/classification/pytorch.py#L404) for loop, depending on `batch_size` and the first dim of `x_preprocessed` it's possible that `i_batch` will end up having a batch_size of 1. This occurs when `x_preprocessed.shape[0] % batch_size == 1`. In my case, `x_preprocessed` is of shape `(39209, 48, 48, 3)` and `batch_size` is 8, and `39209 % 8` is 1. When `i_batch` has batch_size 1, this then causes an error in torch's batch normalization. Specifically in [this](https://github.com/pytorch/pytorch/blob/v1.10.2/torch/nn/functional.py#L2234-L2248) function which is called [here](https://github.com/pytorch/pytorch/blob/v1.10.2/torch/nn/functional.py#L2280). The end result is an error that looks like this:

```
File "/opt/conda/lib/python3.8/site-packages/art/estimators/classification/pytorch.py", line 1115, in forward
    x = module_(x)
        │       └ tensor([[  7.4983,  33.5128,   3.2305,   0.0000,  60.0542,   0.0000,   0.0000,
        │                    0.0000,   0.0000,  11.4205,   0.000...
        └ BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[  7.4983,  33.5128,   3.2305,   0.0000,  60.0542,   0.0000,   0.0000,
           │                          0.0000,   0.0000,  11.4205,   0.00...
           └ <bound method _BatchNorm.forward of BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)>
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
           │ └ <function batch_norm at 0x7f1e6b6bc550>
           └ <module 'torch.nn.functional' from '/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py'>
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
    │                  │     └ <method 'size' of 'torch._C._TensorBase' objects>
    │                  └ tensor([[  7.4983,  33.5128,   3.2305,   0.0000,  60.0542,   0.0000,   0.0000,
    │                               0.0000,   0.0000,  11.4205,   0.000...
    └ <function _verify_batch_size at 0x7f1e6b6bc4c0>
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
                                                                                                      └ torch.Size([1, 300])

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 300])

```

This doesn't appear to be strictly an ART bug but rather an error occurring between the interaction of ART and PyTorch

**To Reproduce**
Call a PyTorch estimator's `fit()` method using a dataset and batch_size such that `# of elements in dataset % batch_size == 1`. Below is a snippet of code that does so:

```
import numpy as np
from armory.baseline_models.pytorch import micronnet_gtsrb
from armory.scenarios.utils import to_categorical

model = micronnet_gtsrb.get_art_model({}, {})
num_batches = 5
x = np.random.randn(num_batches, 48, 48, 3).astype(np.float32)
y = to_categorical(np.random.randint(10, size=num_batches)).astype(np.float32)
model.fit(x, y, batch_size=4, nb_epochs=1
```
Notice that if you change `num_batches` to 6, e.g., the error goes away

Using Armory run: set dataset `"batch_size"` in [this](https://github.com/twosixlabs/armory/blob/v0.15.1/scenario_configs/eval5/poisoning/gtsrb_dlbd_baseline_pytorch.json#L25)  config to 4 or 8 and run `armory run <config>`. 

**System information (please complete the following information):**
 - OS: ubuntu
 - Python version: 3.8.10
 - ART version: 1.10.1
 - PyTorch version: 1.10.2

### PR DESCRIPTION
**Pull request by beat-buesser**
# Description

This pull request adds drop_last option to method `fit` of `PyTorchClassifier`.

Fixes #1723

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by kieranfraser — APPROVED** [review]
Hi Beat, 
This looks good - I've tested locally and the code makes sense. 
Would it be worth wrapping the model prediction in a try-except block and warning the user that a drop_last may be required if this error is caught (as the default is False)?

**Review by kieranfraser — APPROVED** [review]

**Review by kieranfraser — CHANGES_REQUESTED** [review]
`mypy` and `pylint` failing in CI / Style checks. The drop_last option should be included in `PyTorchDeRandomizedSmoothing` and `PyTorchRandomizedSmoothing` fit method too?

**Comment by beat-buesser** [comment]
I think the try-except block is an interesting idea. I'm running a few tests if it would slow down the model training.

**Review by kieranfraser — APPROVED** [review]
Looks good to me!

**Pull request merged**
